# you need : REST Client => https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# to make this file works
###

### List all messages
Get http://localhost:3000/messages

### Get one message
GET http://localhost:3000/messages/12

### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content" : "Hello There!"
}