# you need : REST Client => https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# to make this file works
###
// Variables :
@authHost = http://localhost:3000/auth
@user_email = ic@test.com
@user_password = test

// Routes :
### Create new user
POST {{ authHost }}/signup 
Content-Type: application/json

{
  "email": "{{ user_email }}",
  "password": "{{ user_password }}"
}

### Conect user
POST {{ authHost }}/signin 
Content-Type: application/json

{
  "email": "{{ user_email }}",
  "password": "{{ user_password }}"
}

### Get current user
GET {{ authHost }}/whoami

### Get specific user by id
GET {{ authHost }}/2

### Get specific user by email
GET {{ authHost }}?email=v@test.com

### Delete specific user
DELETE {{ authHost }}/2

### Update specific user
PATCH {{ authHost }}/5
Content-Type: application/json

{
  "email": "{{ user_email }}",
  "password": "{{ user_password }}"
}
