# you need : REST Client => https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# to make this file works
###


### Create new user
POST http://localhost:3000/auth/signup 
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test" 
}
