# you need : REST Client => https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# to make this file works
###


### Create new user
POST http://localhost:3000/auth/signup 
Content-Type: application/json

{
  "email": "x@test.com",
  "password": "test" 
}

### Get specific user by id
GET http://localhost:3000/auth/2

### Get specific user by email
GET http://localhost:3000/auth?email=x@test.com

### Delete specific user
DELETE  http://localhost:3000/auth/2

### Update specific user
PATCH  http://localhost:3000/auth/5
Content-Type: application/json

{
  "email": "xxx@test.com",
  "password": "blou" 
}

###